
// Generated by view binder compiler. Do not edit!
package com.sgpggame.project.databinding;

//package kr.ac.tukorea.ge.spgp2023.dragonflight.databinding;


import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;


import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import com.sgpggame.project.R;
//import kr.ac.tukorea.ge.spgp2023.dragonflight.R;

public final class ActivityTitleBinding implements ViewBinding {
    @NonNull
    private final RelativeLayout rootView;

    @NonNull
    public final ImageView treeImageView;

    @NonNull
    public final LinearLayout treeParentLayout;

    private ActivityTitleBinding(@NonNull RelativeLayout rootView, @NonNull ImageView treeImageView,
                                 @NonNull LinearLayout treeParentLayout) {
        this.rootView = rootView;
        this.treeImageView = treeImageView;
        this.treeParentLayout = treeParentLayout;
    }

    @Override
    @NonNull
    public RelativeLayout getRoot() {
        return rootView;
    }

    @NonNull
    public static ActivityTitleBinding inflate(@NonNull LayoutInflater inflater) {
        return inflate(inflater, null, false);
    }

    @NonNull
    public static ActivityTitleBinding inflate(@NonNull LayoutInflater inflater,
                                               @Nullable ViewGroup parent, boolean attachToParent) {
        View root = inflater.inflate(R.layout.activity_title, parent, false);
        if (attachToParent) {
            parent.addView(root);
        }
        return bind(root);
    }

    @NonNull
    public static ActivityTitleBinding bind(@NonNull View rootView) {
        // The body of this method is generated in a way you would not otherwise write.
        // This is done to optimize the compiled bytecode for size and performance.
        int id;
        missingId: {
            id = R.id.treeImageView;
            ImageView treeImageView = ViewBindings.findChildViewById(rootView, id);
            if (treeImageView == null) {
                break missingId;
            }

            id = R.id.treeParentLayout;
            LinearLayout treeParentLayout = ViewBindings.findChildViewById(rootView, id);
            if (treeParentLayout == null) {
                break missingId;
            }

            return new ActivityTitleBinding((RelativeLayout) rootView, treeImageView, treeParentLayout);
        }
        String missingId = rootView.getResources().getResourceName(id);
        throw new NullPointerException("Missing required view with ID: ".concat(missingId));
    }
}

